name: Flask CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Use the Python version of your choice

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8  # Install flake8 linter

    - name: Lint with flake8
      run: |
        source venv/bin/activate
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Set up SQLite database
      run: |
        python -c "
        import sqlite3;
        conn = sqlite3.connect('students.db');
        conn.execute('''
        CREATE TABLE IF NOT EXISTS students (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          name TEXT NOT NULL,
          age INTEGER NOT NULL,
          grade TEXT NOT NULL,
          subjects TEXT NOT NULL
        )''');
        conn.close();"

    - name: Run Tests
      run: |
        source venv/bin/activate
        python -m unittest discover -s tests

    - name: Upload Test Results (optional)
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: tests

